# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shader',
            fields=[
                ('shader_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('shader_opaque', models.CharField(max_length=200)),
                ('shader_uv', models.IntegerField()),
                ('shader_vertex', models.BooleanField()),
            ],
        ),
    ]
