# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-03 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shader',
            name='shader_wikiVersion',
            field=models.IntegerField(default=0),
        ),
    ]
