# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-04 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shader', '0002_shader_shader_wikiversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='shader',
            name='shader_info',
            field=models.CharField(default=b'placeholder', max_length=200),
        ),
    ]
