# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shader', '0002_delete_shader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shader',
            fields=[
                ('shader_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('shader_vertexColor', models.BooleanField()),
                ('shader_uvSet', models.IntegerField()),
                ('shader_surfaceType', models.IntegerField()),
                ('shader_complexity', models.IntegerField()),
                ('shader_textures', models.IntegerField()),
                ('shader_diffuseTex', models.IntegerField()),
                ('shader_normalTex', models.IntegerField()),
                ('shader_SMDTex', models.IntegerField()),
                ('shader_uvTint', models.BooleanField()),
                ('shader_maskTint', models.BooleanField()),
                ('shader_globalDirt', models.BooleanField()),
                ('shader_emissive', models.BooleanField()),
                ('shader_wetness', models.BooleanField()),
                ('shader_parallax', models.BooleanField()),
                ('shader_retroReflect', models.BooleanField()),
            ],
        ),
    ]
