# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-04 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shader', '0003_shader_shader_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shader',
            name='shader_info',
        ),
    ]
