# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to=b'whereYouAre')),
                ('time', models.DateTimeField()),
                ('vote_problem', models.IntegerField(default=0)),
                ('vote_useful', models.IntegerField(default=0)),
            ],
        ),
    ]
