# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shader',
            fields=[
                ('shader_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('shader_info', models.CharField(max_length=255)),
                ('shader_url', models.CharField(max_length=255)),
                ('shader_p4', models.CharField(max_length=255)),
            ],
        ),
    ]
